version: '3.1'

services:
  cron:
    image: cowrvalera/docker-cron-php:v1.2.0
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./src:/var/www/html
      - ./cron.d:/etc/cron.d
