version: '3.1'

services:
  cron:
    image: cowrvalera/docker-cron-php:v1.0.1
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./src:/var/www/html
      - ./crontab:/var/spool/cron/crontabs/www-data
